tables:
  - name: CUSTOMER_MASTER
    db_type: MySQL
    key_column: customer_id
    columns:
      - customer_id
      - name
      - pan
      - aadhaar
      - state
      - DP_ID
  - name: client_master
    db_type: PostgreSQL
    key_column: clt_lwcustid
    columns:
      - clt_lwcustid
      - name
      - pan
      - adhr

#tables:
#  - name: client_master
#    db_type: PostgreSQL
#    key_column: clt_lwcustid
#    columns:
#      - clt_lwcustid
#      - name
#      - pan
#      - adhr
#  - name: CUSTOMER_MASTER
#    db_type: MySQL
#    key_column: customer_id
#    columns:
#      - customer_id
#      - name
#      - pan
#      - aadhaar
#      - state
#      - DP_ID
